### ISSUE TITLE
/list & /listall displaying previous username

### ISSUE THREAD

**Issue by ghost** [Ruinscraft/ruinscraft-chat#15]
![image](https://user-images.githubusercontent.com/53756203/105849747-b76ed200-5fd8-11eb-9864-1c1d1c57e41b.png)
![image](https://user-images.githubusercontent.com/53756203/105849834-d2d9dd00-5fd8-11eb-8171-819ca1f9cd0c.png)

**Comment by ds58** [comment]
If you logout, wait 10 seconds, then login, does it update?

**Comment by ds58** [comment]
Should be fixed with 8729e83aaccc19d821887981ed4ed0428d8ed36e
